package com.goviet.keyboard.ui

val secondaryKeyMap = mapOf(
    "q" to "@", "w" to "#", "e" to "₫", "r" to "_", "t" to "&",
    "y" to "-", "u" to "+", "i" to "(", "o" to ")", "p" to "*",
    "a" to "!", "s" to "?", "d" to "\"", "f" to "'", "g" to ":",
    "h" to ";", "j" to "/", "k" to "~", "l" to "\\",
    "z" to "%", "x" to "<", "c" to ">", "v" to "[", "b" to "]",
    "n" to "{", "m" to "}"
)

val longPressSymbolMap = mapOf(
    "q" to listOf("@"),
    "w" to listOf("#"),
    "e" to listOf("₫", "$", "€", "£", "¥", "₩", "¢"),
    "r" to listOf("_", "—"),
    "t" to listOf("&", "§"),
    "y" to listOf("-", "–", "—"),
    "u" to listOf("+", "±"),
    "i" to listOf("(", "[", "{"),
    "o" to listOf(")", "]"),
    "p" to listOf("*"),
    "a" to listOf("!", "¡"),
    "s" to listOf("?", "¿"),
    "d" to listOf("\"", "“", "”", "„"),
    "f" to listOf("'", "`"),
    "g" to listOf(":", "："),
    "h" to listOf(";", "；"),
    "j" to listOf("/", "\\", "|"),
    "k" to listOf("~", "`"),
    "l" to listOf("\\"),
    "z" to listOf("%", "‰"),
    "x" to listOf("<", "«"),
    "c" to listOf(">", "»"),
    "v" to listOf("[", "⟨"),
    "b" to listOf("]", "⟩"),
    "n" to listOf("{", "}"),
    "m" to listOf("}")
)

val symbolLongPressMap = mapOf(
    "1" to listOf("¹", "½", "⅓", "¼"),
    "2" to listOf("²", "⅔"),
    "3" to listOf("³", "¾", "⅜"),
    "4" to listOf("⁴"),
    "5" to listOf("⁵", "⅝"),
    "6" to listOf("⁶"),
    "7" to listOf("⁷", "⅞"),
    "8" to listOf("⁸"),
    "9" to listOf("⁹"),
    "0" to listOf("⁰"),
    "₫" to listOf("$", "€", "£", "¥", "₩", "¢"),
    "$" to listOf("₫", "€", "£", "¥", "₩"),
    "!" to listOf("¡"),
    "?" to listOf("¿"),
    "-" to listOf("–", "—", "·"),
    "\"" to listOf("“", "”"),
    "'" to listOf("‘", "’"),
    "%" to listOf("‰"),
    "+" to listOf("±"),
    "/" to listOf("\\", "|"),
    "\\" to listOf("/"),
    "|" to listOf("/"),
    "`" to listOf("~"),
    "=" to listOf("≠", "≈"),
    "<" to listOf("≤", "«"),
    ">" to listOf("≥", "»"),
    "^" to listOf("↑"),
    "&" to listOf("§"),
    "*" to listOf("★"),
    "(" to listOf("[", "{"),
    ")" to listOf("]"),
    "[" to listOf("{"),
    "]" to listOf("}"),
    "{" to listOf("["),
    "}" to listOf("]"),
    "~" to listOf("`"),
    "•" to listOf("★"),
    "," to listOf(";", "、"),
    "." to listOf("…", ".com", ".vn"),
    "€" to listOf("$", "£"),
    "£" to listOf("€", "$"),
    "¥" to listOf("₩"),
    "₩" to listOf("¥"),
    "°" to listOf("℃", "℉"),
    "±" to listOf("+"),
    "−" to listOf("-"),
    "×" to listOf("*"),
    "÷" to listOf("/"),
    "≠" to listOf("="),
    "≈" to listOf("~"),
    "≤" to listOf("<"),
    "≥" to listOf(">"),
    "“" to listOf("\""),
    "”" to listOf("\""),
    "‘" to listOf("'"),
    "’" to listOf("'"),
    "«" to listOf("<"),
    "»" to listOf(">"),
    "©" to listOf("®", "™")
)



